services:
  app:
    build: .
    restart: unless-stopped
    volumes:
      - .:/app
      - app-data:/app/data
    environment:
      - UV_COMPILE_BYTECODE=1
      - UV_LINK_MODE=copy
    working_dir: /app
    command: ["uv", "run", "main.py"]
    networks:
      - telibot_network

volumes:
  app-data:

networks:
  telibot_network:
    driver: bridge
